spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=atlas_test_123
spring.data.mongodb.auto-index-creation=true
weather.api.key=${WEATHER_API_KEY}

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MY_GMAIL}
spring.mail.password=${MY_GMAIL_PASS}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=${PORT:8080}

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret=${JWT_SECRET}


# Kafka cluster
#spring.kafka.bootstrap-servers=lkc-1255163.ap-south-1.aws.public.confluent.cloud:9092
#
## Authentication
#spring.kafka.properties.security.protocol=SASL_SSL
#spring.kafka.properties.sasl.mechanism=PLAIN
#
#spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='<username>' password='<password>';
#
## Producer
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
#
# Consumer
##spring.kafka.consumer.group-id=orders-group
#spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
#
##spring.kafka.consumer.properties[spring.json.value.default.type]=com.mongpro.mongo_project.Kafka.Orders
#spring.kafka.consumer.properties[spring.json.value.default.type]=com.mongpro.mongo_project.Kafka.Report
#spring.kafka.consumer.properties[spring.json.trusted.packages]=com.mongpro.mongo_project.Kafka